In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score,precision_score,recall_score,f1_score

In [14]:
df=pd.read_csv(r"D:\Disk G\ML Supervise Learning Project\student_performance.csv")

In [15]:
df

     study_hours  attendance  assignments  previous_score  final_result
0              5          50            4              50             1
1              6          99            5              48             0
2              2          75            7              53             0
3              3          64            4              48             0
4              6          82            1              78             0
..           ...         ...          ...             ...           ...
995            2          71            6              41             0
996            8          87            9              48             1
997            6          82            3              48             0
998            7          71            2              52             0
999            1          93            0              45             1

[1000 rows x 5 columns]

In [16]:
df.isnull().sum()

study_hours       0
attendance        0
assignments       0
previous_score    0
final_result      0
dtype: int64

In [17]:
df.duplicated().sum()

np.int64(1)

In [18]:
df.drop_duplicates(inplace=True)

In [19]:
df

     study_hours  attendance  assignments  previous_score  final_result
0              5          50            4              50             1
1              6          99            5              48             0
2              2          75            7              53             0
3              3          64            4              48             0
4              6          82            1              78             0
..           ...         ...          ...             ...           ...
995            2          71            6              41             0
996            8          87            9              48             1
997            6          82            3              48             0
998            7          71            2              52             0
999            1          93            0              45             1

[999 rows x 5 columns]

In [35]:
df[df["previous_score"]<=50]

     study_hours  attendance  assignments  previous_score  final_result
0              5          50            4              50             1
1              6          99            5              48             0
3              3          64            4              48             0
6              9          96            9              42             0
11             2          61            7              46             1
..           ...         ...          ...             ...           ...
992            9          77            8              47             0
995            2          71            6              41             0
996            8          87            9              48             1
997            6          82            3              48             0
999            1          93            0              45             1

[210 rows x 5 columns]

In [36]:
x=df[["study_hours","attendance","assignments","previous_score"]]
y=df["final_result"]
X_train,X_test,Y_train,Y_test=train_test_split(x,y,test_size=0.2,random_state=30)

In [37]:
model=LogisticRegression()

In [38]:
model.fit(X_train,Y_train)

LogisticRegression()

In [39]:
prediction=model.predict(X_test)

In [40]:
accs=accuracy_score(Y_test,prediction)
ps=precision_score(Y_test,prediction)
rs=recall_score(Y_test,prediction)
fs=f1_score(Y_test,prediction)

In [41]:
accs,ps,rs,fs

(0.465, 0.5517241379310345, 0.41379310344827586, 0.4729064039408867)